### PR TITLE
[wip] adding nft proposal components

### PR DESCRIPTION
**Pull request by iainnash**
Screen Shot 2021-06-09 at 4 37 22 PM

### CODE REVIEW

**Comment by iainnash** [comment]
Left to do:
1. Add {check} and {x} buttons
2. write unit tests

**Comment by iainnash** [comment]
Screen Shot 2021-06-11 at 4 27 44 PM
Screen Shot 2021-06-11 at 4 27 08 PM

**Comment by dblodorn** [comment]
@iainnash will this be released to npm? nft-proposal not available in main branch or dist folder in "^0.0.19-pre"

**Comment by iainnash** [comment]
@dblodorn released :)

**Pull request merged**
